services:
  postgres:
    image: postgres:16
    container_name: metrics-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_password
      POSTGRES_DB: metrics_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U default_user -d metrics_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: