name: gwin-chart
home: ""
sources: []
version: v1.0.10
description: ""
keywords: []
maintainers:
    - name: Eugeny Kuznetsov
      email: eugenschmidt@yandex-team.ru
      url: ""
    - name: Ivan Tarasov
      email: vaniog@yandex-team.ru
      url: ""
icon: ""
apiversion: v2
condition: ""
tags: ""
appversion: v1.0.10
deprecated: false
annotations: {}
kubeversion: ""
dependencies: []
type: ""
