apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- toYaml .Values.controller.labels | nindent 4 }}
  name: {{ .Values.controller.names.deployment }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # This value of maxSurge means that during a rolling update
      # the new ReplicaSet will be created first.
      maxSurge: 50%
  selector:
    matchLabels:
      {{- toYaml .Values.controller.labels | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.controller.metrics.port }}"
      labels:
        {{- toYaml .Values.controller.labels | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- toYaml .Values.controller.labels | nindent 18 }}
              topologyKey: kubernetes.io/hostname
            weight: 100
      {{- if .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.controller.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.tolerations }}
      tolerations:
        {{- toYaml .Values.controller.tolerations | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- include "gwin.controller.image.pullSecrets" . | nindent 8 }}
      containers:
      - name: {{ .Values.controller.names.deployment }}
        command: ["/bin/gwin"]
        args:
        - serve
        - --incluster
        - --disable-leader-election
        {{ if .Values.controller.defaultBalancerSubnets }}
        - --subnet-ids={{ .Values.controller.defaultBalancerSubnets | join "," }}
        {{- end }}
        - --folder-id={{ .Values.controller.folderId }}
        - --api-endpoint={{ .Values.controller.ycApiEndpoint }}
        - --metrics-port={{ .Values.controller.metrics.port }}
        - --metrics-address={{ .Values.controller.metrics.address }}
        - --cloud-labels-prefix={{ .Values.controller.cloudLabelsPrefix }}
        - --cloud-labels-owner={{ .Values.controller.cloudLabelsOwner }}
        {{- if .Values.controller.debugLogs }}
        - --debug
        {{- end }}
        {{- if .Values.controller.disableCertificatesListing }}
        - --disable-certificates-listing
        {{- end }}
        {{ if .Values.nodecheck.enabled }}
        - --nodecheck-enabled
        - --nodecheck-port={{ .Values.nodecheck.service.nodePort }}
        - --nodecheck-interval={{ .Values.nodecheck.healthcheck.interval }}
        - --nodecheck-timeout={{ .Values.nodecheck.healthcheck.timeout }}
        - --nodecheck-healthy-threshold={{ .Values.nodecheck.healthcheck.healthyThreshold }}
        - --nodecheck-unhealthy-threshold={{ .Values.nodecheck.healthcheck.unhealthyThreshold }}
        {{ end }}
        {{- if eq (include "gwin.controller.authMethod" .) "workloadIdentityFederation" }}
        - --use-instance-service-account
        {{- end }}
        {{ if .Values.controller.extraArgs }}
          {{ range .Values.controller.extraArgs }}
        - {{ . }}
          {{ end }}
        {{ end }}
        image: "{{ .Values.controller.image.name }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ include "gwin.controller.image.pullPolicy" . }}
        securityContext:
          {{- include "gwin.controller.containerSecurityContext" . | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        {{- if eq (include "gwin.controller.authMethod" .) "secret" }}
        - name: yc-token
          mountPath: /certs
          readOnly: true
        {{- end }}
        {{- if .Values.controller.customRootCa.secret.name }}
        - name: custom-root-ca
          mountPath: /etc/ssl/certs
          readOnly: true
        {{- end }}
        env:
        - name: GATEWAY_CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        {{- if .Values.controller.grpcLog.verbosityLevel }}
        - name: "GRPC_GO_LOG_VERBOSITY_LEVEL"
          value: "{{ .Values.controller.grpcLog.verbosityLevel }}"
        {{- end }}
        {{- if .Values.controller.grpcLog.severityLevel }}
        - name: "GRPC_GO_LOG_SEVERITY_LEVEL"
          value: "{{ .Values.controller.grpcLog.severityLevel }}"
        {{- end }}
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ .Values.controller.names.serviceAccount }}
      securityContext:
        {{- include "gwin.controller.podSecurityContext" . | nindent 8 }}
      volumes:
      {{- if eq (include "gwin.controller.authMethod" .) "secret" }}
      - name: yc-token
        secret:
          secretName: {{ .Values.controller.ycServiceAccount.secret.name }}
          items:
          - key: {{ .Values.controller.ycServiceAccount.secret.key }}
            path: yc-token
      {{- end }}
      {{- if .Values.controller.customRootCa.secret.name }}
      - name: custom-root-ca
        secret:
          defaultMode: 420
          secretName: {{ .Values.controller.customRootCa.secret.name }}
          items:
            - key: {{ .Values.controller.customRootCa.secret.key }}
              path: ca-certificates.crt
      {{- end }}
