apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.names.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  {{- if eq (include "gwin.controller.authMethod" .) "workloadIdentityFederation" }}
  annotations:
    yandex.cloud/federated-yc-service-account-id: {{ .Values.controller.ycServiceAccount.workloadIdentityFederation.serviceAccountID }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.controller.names.clusterRoleBinding }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.controller.names.clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.controller.names.serviceAccount }}
  namespace: {{ .Release.Namespace }}
