{{- if eq (include "gwin.controller.authMethod" .) "secret" }}
{{ if .Values.controller.ycServiceAccount.secret.create }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controller.ycServiceAccount.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.controller.ycServiceAccount.secret.key }} : {{ .Values.controller.ycServiceAccount.secret.value | b64enc }}

---
{{- end }}
{{- end }}


{{ if .Values.controller.customRootCa.secret.create }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controller.customRootCa.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.controller.customRootCa.secret.key }} : {{ .Values.controller.customRootCa.secret.value | b64enc }}

{{ end }}
